#pragma once

// This file is generated by the binding generator.
// It declares the GDExtension initialization hooks for the module.
//
// The corresponding implementation defines the entry point:
//   GDExtensionBool GDE_EXPORT ocgd_library_init(...)
// and calls the functions declared below.
//
// Keep this header minimal to avoid unnecessary compile-time dependencies.

#include <godot_cpp/godot.hpp>
#include <godot_cpp/core/defs.hpp>

extern "C" {
    GDExtensionBool GDE_EXPORT ocgd_ai_library_init(GDExtensionInterfaceGetProcAddress p_get_proc_address, GDExtensionClassLibraryPtr p_library, GDExtensionInitialization *r_initialization);
}
